In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

***Load data***

In [25]:
df=pd.read_csv('student_performance.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

***Assign x and y***

In [26]:
x=df.drop(columns='Performance Index')
y= df['Performance Index']

***Train_test_split***

In [27]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,train_size=0.8,random_state=42)

In [28]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,No,7,5
1561,2,48,Yes,7,6
1670,2,81,No,7,2
6087,2,46,No,6,1
6669,8,47,No,9,0
...,...,...,...,...,...
5734,8,50,Yes,6,6
5191,4,68,No,9,3
5390,9,48,No,7,6
860,1,47,No,9,0
7270,2,46,No,6,6

In [29]:
num_cols=x.select_dtypes(include='number').columns
obj_cols=x.select_dtypes(include='object').columns

C:\Users\KAPIL SHARMA\AppData\Local\Temp\ipykernel_20032\4193232358.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols=x.select_dtypes(include='object').columns

In [30]:
preprocessing=ColumnTransformer(
    transformers=[
        ('encoder',OneHotEncoder(handle_unknown='ignore'),obj_cols),
        ('scaling',StandardScaler(),num_cols)
    ]
)

In [31]:
preprocessing.fit_transform(xtrain)

array([[ 1.        ,  0.        ,  0.00645547, -1.18384439,  0.26988848,
         0.13404112],
       [ 0.        ,  1.        , -1.14974745, -1.24150571,  0.26988848,
         0.48356164],
       [ 1.        ,  0.        , -1.14974745,  0.66131759,  0.26988848,
        -0.91452044],
       ...,
       [ 1.        ,  0.        ,  1.54805935, -1.24150571,  0.26988848,
         0.48356164],
       [ 1.        ,  0.        , -1.53514842, -1.29916702,  1.4474766 ,
        -1.61356148],
       [ 1.        ,  0.        , -1.14974745, -1.35682833, -0.31890558,
         0.48356164]], shape=(8000, 6))

In [32]:
preprocessing

ColumnTransformer(transformers=[('encoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 Index(['Extracurricular Activities'], dtype='str')),
                                ('scaling', StandardScaler(),
                                 Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced'],
      dtype='str'))])