In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [57]:
df=pd.DataFrame(data={
    "color": ["red","blue","green","blue","red","green","green","green","red","blue"],
    "size": ["S","M","L","XL","S","L","S","M","XL","M"],
    "shape": ["circle","square","triangle","circle","square","triangle","triangle","circle","square","circle"],
    "target": ["class1","class2","class1","class2","class1","class2","class1","class2","class1","class2"]
})
df

   color size     shape  target
0    red    S    circle  class1
1   blue    M    square  class2
2  green    L  triangle  class1
3   blue   XL    circle  class2
4    red    S    square  class1
5  green    L  triangle  class2
6  green    S  triangle  class1
7  green    M    circle  class2
8    red   XL    square  class1
9   blue    M    circle  class2

In [58]:
x=df.drop(columns='target')
y=df['target']

In [59]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8, random_state=42)

In [60]:
xtrain

   color size     shape
5  green    L  triangle
0    red    S    circle
7  green    M    circle
2  green    L  triangle
9   blue    M    circle
4    red    S    square
3   blue   XL    circle
6  green    S  triangle

In [61]:
encoder= OneHotEncoder()
encoder.fit_transform(xtrain[['color','size','shape']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 24 stored elements and shape (8, 10)>

In [62]:
print(encoder.get_feature_names_out())
print(type(encoder.fit_transform(xtrain[['color','size','shape']])))

['color_blue' 'color_green' 'color_red' 'size_L' 'size_M' 'size_S'
 'size_XL' 'shape_circle' 'shape_square' 'shape_triangle']
<class 'scipy.sparse._csr.csr_matrix'>

In [63]:
encoder.fit_transform(xtrain[['color','size','shape']]).toarray()      # For assigning numerical value

array([[0., 1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [64]:
encoder.transform(xtest)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (2, 10)>

In [65]:
encoder.fit_transform(xtest[['color','size','shape']]).toarray()

array([[0., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.]])

In [66]:
# encoder= OneHotEncoder(handle_unknown="ignore",sparse_output=False)
encoder=OneHotEncoder()
new_input=[['green','L','triangle']]
encoder.transform(xtest[['color','size','shape']]).toarray()

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.